### ISSUE TITLE
Cannot connect to mongodb on debian

### ISSUE THREAD

**Issue by lijiarui** [lijiarui/robot_ts#1]
```
root@wechatytest:~/robot_ts# cd robot_ts/
root@wechatytest:~/robot_ts# wechaty src/index.ts

/bot/node_modules/mongodb-core/lib/topologies/server.js:326
        return self.emit('error', new MongoError(f('failed to connect to server [%s] on first connect', self.name)));
                                  ^
MongoError: failed to connect to server [localhost:27017] on first connect
    at Pool.<anonymous> (/bot/node_modules/mongodb-core/lib/topologies/server.js:326:35)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:189:7)
    at Connection.<anonymous> (/bot/node_modules/mongodb-core/lib/connection/pool.js:270:12)
    at Object.onceWrapper (events.js:291:19)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:192:7)
    at Socket.<anonymous> (/bot/node_modules/mongodb-core/lib/connection/connection.js:175:49)
    at Object.onceWrapper (events.js:291:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
    at emitErrorNT (net.js:1280:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

acutually, I have started mongodb

**Comment by lijiarui** [comment]
服务器可以跑通mongodb的测试代码：
```
var MongoClient = require('mongodb').MongoClient;
var assert = require('assert');

var url = 'mongodb://localhost:27017/test';
MongoClient.connect(url, function(err, db) {
  assert.equal(null, err);
  console.log("Connected correctly to server~~~~.");
  db.close();
});
```

但是下面代码本机可以跑通，服务器失败
```
import * as mongoose from 'mongoose';
import Settings from '../../config/Settings';
import log from '../../config/Logger';

class DataAccess {
    static _mongooseInstance: any;
    static _mongooseConnection: mongoose.Connection;

    constructor() {
        DataAccess.connect();
    }
    // TODO add connect options
    static connect(): mongoose.Connection {
        if (this._mongooseInstance) return this._mongooseInstance;

        this._mongooseConnection = mongoose.connection;
        this._mongooseConnection.once('open', (err) => {
            log.info("connect to mongo db");
            if (err) console.log(err)
        });
        this._mongooseInstance = mongoose.connect(Settings.ROBOT_DB);
        return this._mongooseInstance;

    }
}

DataAccess.connect();
```


本机正常运行结果：
```
➜  robot_ts git:(master) ✗ ts-node src/app/dataAccess/DataAccess.ts
info: connect to mongo db
```

服务器运行结果：
```
[root@meituan robot_ts]# ts-node src/app/dataAccess/DataAccess.ts

/usr/lib/node_modules/ts-node/dist/index.js:47
        .update(os_1.homedir(), 'utf8')
                     ^
TypeError: Object #<Object> has no method 'homedir'
    at getTmpDir (/usr/lib/node_modules/ts-node/dist/index.js:47:22)
    at Object.register (/usr/lib/node_modules/ts-node/dist/index.js:62:79)
    at Object.<anonymous> (/usr/lib/node_modules/ts-node/dist/_bin.js:90:23)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
```

**Comment by lijiarui** [comment]
上面的问题是node 版本的问题，升级到node7后没有问题了。

接下来服务器出现了很奇怪的问题：

如果使用node启动服务，是可以连接到mongd的,忽略中间chromedriver错误可以看到信息：`info: connect to mongo db`
```
[root@meituan robot_ts]# ts-node src/index.ts
INFO Wechaty v0.7.33 initializing...
INFO Wechaty v0.7.33 initializing...
ERR Wechaty init() already inited. return and do nothing.
Express Server listening on port 3000
info: wechaty robot init finished!
ERR PuppetWebBrowserDriver initChromeDriver() Wechaty require `chromedriver` to be installed.(try to run: "npm install chromedriver" to fix this issue)
ERR PuppetWebBrowser init() exception: The ChromeDriver could not be found on the current PATH. Please download the latest version of the ChromeDriver from http://chromedriver.storage.googleapis.com/index.html and ensure it can be found on your PATH.
WARN PuppetWebBrowser quit() exception: Cannot read property 'close' of undefined
WARN PuppetWebBrowser driver.quit() exception: Cannot read property 'close' of undefined
ERR PuppetWeb initBrowser() exception: The ChromeDriver could not be found on the current PATH. Please download the latest version of the ChromeDriver from http://chromedriver.storage.googleapis.com/index.html and ensure it can be found on your PATH.
ERR PuppetWeb init() exception: Error: The ChromeDriver could not be found on the current PATH. Please download the latest version of the ChromeDriver from http://chromedriver.storage.googleapis.com/index.html and ensure it can be found on your PATH.
    at ServiceBuilder (/root/robot_ts/node_modules/selenium-webdriver/chrome.js:191:13)
    at getDefaultService (/root/robot_ts/node_modules/selenium-webdriver/chrome.js:280:22)
    at Function.createSession (/root/robot_ts/node_modules/selenium-webdriver/chrome.js:700:44)
    at createDriver (/root/robot_ts/node_modules/selenium-webdriver/index.js:167:33)
    at Builder.build (/root/robot_ts/node_modules/selenium-webdriver/index.js:639:16)
    at BrowserDriver.<anonymous> (/root/robot_ts/node_modules/wechaty/src/puppet-web/browser-driver.ts:130:24)
    at Generator.next (<anonymous>)
    at /root/robot_ts/node_modules/wechaty/dist/src/puppet-web/browser-driver.js:7:71
    at __awaiter (/root/robot_ts/node_modules/wechaty/dist/src/puppet-web/browser-driver.js:3:12)
    at BrowserDriver.initChromeDriver (/root/robot_ts/node_modules/wechaty/dist/src/puppet-web/browser-driver.js:52:16)
    at BrowserDriver.<anonymous> (/root/robot_ts/node_modules/wechaty/src/puppet-web/browser-driver.ts:46:20)
    at Generator.next (<anonymous>)
    at /root/robot_ts/node_modules/wechaty/dist/src/puppet-web/browser-driver.js:7:71
    at __awaiter (/root/robot_ts/node_modules/wechaty/dist/src/puppet-web/browser-driver.js:3:12)
    at BrowserDriver.init (/root/robot_ts/node_modules/wechaty/dist/src/puppet-web/browser-driver.js:27:16)
    at Browser.<anonymous> (/root/robot_ts/node_modules/wechaty/src/puppet-web/browser.ts:84:25)
ERR Config ###########################
ERR Config unhandledRejection: TypeError: Cannot read property 'quit' of undefined [object Promise]
ERR Config ###########################
ERR Config unhandledRejection::catch(Cannot read property 'quit' of undefined)
(node:597) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 4)
info: connect to mongo db
```

因为chromedriver的问题，只能用docker

```
[root@meituan robot_ts]# docker run -t -i --rm --volume="$(pwd)":/bot --name=bot zixia/wechaty:latest src/index.ts

 __        __        _           _
 \ \      / /__  ___| |__   __ _| |_ _   _
  \ \ /\ / / _ \/ __| '_ \ / _` | __| | | |
   \ V  V /  __/ (__| | | | (_| | |_| |_| |
    \_/\_/ \___|\___|_| |_|\__,_|\__|\__, |
                                     |___/
____________________________________________________
            https://www.wechaty.io
  ____                            _   _
 / ___|___  _ __  _ __   ___  ___| |_(_)_ __   __ _
| |   / _ \| '_ \| '_ \ / _ \/ __| __| | '_ \ / _` |
| |__| (_) | | | | | | |  __/ (__| |_| | | | | (_| |
 \____\___/|_| |_|_| |_|\___|\___|\__|_|_| |_|\__, |
                                              |___/
  ____ _           _   ____        _
 / ___| |__   __ _| |_| __ )  ___ | |_ ___
| |   | '_ \ / _` | __|  _ \ / _ \| __/ __|
| |___| | | | (_| | |_| |_) | (_) | |_\__ \
 \____|_| |_|\__,_|\__|____/ \___/ \__|___/


Starting Wechaty ... v0.7.33

Working directory: /bot
Install dependencies modules ...
Skipped yarn. Please make sure you had installed all the NPM modules which is depended by your bot script.
Executing ts-node src/index.ts
INFO Wechaty v0.7.33 initializing...
INFO Wechaty v0.7.33 initializing...
ERR Wechaty init() already inited. return and do nothing.
Express Server listening on port 3000
info: wechaty robot init finished!

/bot/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:326
        return self.emit('error', new MongoError(f('failed to connect to server [%s] on first connect', self.name)));
                                  ^
MongoError: failed to connect to server [localhost:27017] on first connect
    at Pool.<anonymous> (/bot/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:326:35)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:189:7)
    at Connection.<anonymous> (/bot/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:270:12)
    at Object.onceWrapper (events.js:291:19)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:192:7)
    at Socket.<anonymous> (/bot/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:175:49)
    at Object.onceWrapper (events.js:291:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
    at emitErrorNT (net.js:1280:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by zixia** [comment]
```shell
[root@meituan robot_ts]# docker run -t -i --rm --volume="$(pwd)":/bot --name=bot zixia/wechaty:latest src/index.ts
```

You forgot something I had told you before in this command.

**Comment by lijiarui** [comment]
```
[root@meituan robot_ts]# docker run -t -i --rm -p 127.0.0.1:27017:27017 --volume="$(pwd)":/bot --name=bot zixia/wechaty:latest src/index.ts
docker: Error response from daemon: driver failed programming external connectivity on endpoint bot (0d0c5394845c99050ed0cb7bc1bee35999b96566a17fc9c72ecfd99bb05d9669): Error starting userland proxy: listen tcp 127.0.0.1:27017: bind: address already in use.
[root@meituan robot_ts]# docker run -t -i --rm -p 27017:27017 --volume="$(pwd)":/bot --name=bot zixia/wechaty:latest src/index.ts
docker: Error response from daemon: driver failed programming external connectivity on endpoint bot (8f28c3eb948b6549ed9f792366fe334d2d850f6449adc36c81f89290e3748cbb): Error starting userland proxy: listen tcp 0.0.0.0:27017: bind: address already in use.
```

**Comment by zixia** [comment]
not this parameter. I mean the other parameters : `--privileged` and `--net=host`

**Comment by lijiarui** [comment]
```
[root@meituan robot_ts]# docker run -t -i --rm --privileged --net=host --volume="$(pwd)":/bot --name=bot zixia/wechaty:latest src/index.ts
```

fix! @zixia Thanks
